### ISSUE TITLE
ModuleNotFoundError: No module named 'stanfit4anon_model_b4891e6a918b5730463fee7aa1953d40_754069134334311752

### ISSUE THREAD

**Issue by yezhengli-Mr9** [mwestt/An-Introduction-to-Bayesian-Inference-in-PyStan#1]
It will report 
```python
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_b4891e6a918b5730463fee7aa1953d40 NOW.
Process SpawnPoolWorker-8:
Process SpawnPoolWorker-9:
Traceback (most recent call last):
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_b4891e6a918b5730463fee7aa1953d40_1896197151010203272'
Traceback (most recent call last):
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_b4891e6a918b5730463fee7aa1953d40_1896197151010203272'
Process SpawnPoolWorker-12:
Traceback (most recent call last):
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_b4891e6a918b5730463fee7aa1953d40_1896197151010203272'
Process SpawnPoolWorker-15:
Traceback (most recent call last):
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/yezli/miniconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_b4891e6a918b5730463fee7aa1953d40_1896197151010203272'
```
after minor adjustment
```python
# https://towardsdatascience.com/an-introduction-to-bayesian-inference-in-pystan-c27078e58d53
import pystan, pickle
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
if __name__=='__main__':
	sns.set()  # Nice plot aesthetic
	np.random.seed(101)

	model = """
	// Copyright (c) Facebook, Inc. and its affiliates.

// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

functions {
  matrix get_changepoint_matrix(vector t, vector t_change, int T, int S) {
    // Assumes t and t_change are sorted.
    matrix[T, S] A;
    row_vector[S] a_row;
    int cp_idx;

    // Start with an empty matrix.
    A = rep_matrix(0, T, S);
    a_row = rep_row_vector(0, S);
    cp_idx = 1;

    // Fill in each row of A.
    for (i in 1:T) {
      while ((cp_idx <= S) && (t[i] >= t_change[cp_idx])) {
        a_row[cp_idx] = 1;
        cp_idx = cp_idx + 1;
      }
      A[i] = a_row;
    }
    return A;
  }

  // Logistic trend functions

  vector logistic_gamma(real k, real m, vector delta, vector t_change, int S) {
    vector[S] gamma;  // adjusted offsets, for piecewise continuity
    vector[S + 1] k_s;  // actual rate in each segment
    real m_pr;

    // Compute the rate in each segment
    k_s = append_row(k, k + cumulative_sum(delta));

    // Piecewise offsets
    m_pr = m; // The offset in the previous segment
    for (i in 1:S) {
      gamma[i] = (t_change[i] - m_pr) * (1 - k_s[i] / k_s[i + 1]);
      m_pr = m_pr + gamma[i];  // update for the next segment
    }
    return gamma;
  }

  vector logistic_trend(
    real k,
    real m,
    vector delta,
    vector t,
    vector cap,
    matrix A,
    vector t_change,
    int S
  ) {
    vector[S] gamma;

    gamma = logistic_gamma(k, m, delta, t_change, S);
    return cap .* inv_logit((k + A * delta) .* (t - (m + A * gamma)));
  }

  // Linear trend function

  vector linear_trend(
    real k,
    real m,
    vector delta,
    vector t,
    matrix A,
    vector t_change
  ) {
    return (k + A * delta) .* t + (m + A * (-t_change .* delta));
  }

  // Flat trend function

  vector flat_trend(
    real m,
    int T
  ) {
    return rep_vector(m, T);
  }
}

data {
  int T;                // Number of time periods
  int<lower=1> K;       // Number of regressors
  vector[T] t;          // Time
  vector[T] cap;        // Capacities for logistic trend
  vector[T] y;          // Time series
  int S;                // Number of changepoints
  vector[S] t_change;   // Times of trend changepoints
  matrix[T,K] X;        // Regressors
  vector[K] sigmas;     // Scale on seasonality prior
  real<lower=0> tau;    // Scale on changepoints prior
  int trend_indicator;  // 0 for linear, 1 for logistic, 2 for flat
  vector[K] s_a;        // Indicator of additive features
  vector[K] s_m;        // Indicator of multiplicative features
}

transformed data {
  matrix[T, S] A;
  A = get_changepoint_matrix(t, t_change, T, S);
}

parameters {
  real k;                   // Base trend growth rate
  real m;                   // Trend offset
  vector[S] delta;          // Trend rate adjustments
  real<lower=0> sigma_obs;  // Observation noise
  vector[K] beta;           // Regressor coefficients
}

transformed parameters {
  vector[T] trend;
  if (trend_indicator == 0) {
    trend = linear_trend(k, m, delta, t, A, t_change);
  } else if (trend_indicator == 1) {
    trend = logistic_trend(k, m, delta, t, cap, A, t_change, S);
  } else if (trend_indicator == 2) {
    trend = flat_trend(m, T);
  }
}

model {
  //priors
  k ~ normal(0, 5);
  m ~ normal(0, 5);
  delta ~ double_exponential(0, tau);
  sigma_obs ~ normal(0, 0.5);
  beta ~ normal(0, sigmas);

  // Likelihood
  y ~ normal(
  trend
  .* (1 + X * (beta .* s_m))
  + X * (beta .* s_a),
  sigma_obs
  );
}
	"""
	# # Compile the model
	sm = pystan.StanModel(model_code=model)

	# Train the model and generate samples
	stan_init.update(dat)
	fit = sm.sampling(data=stan_init,iter=1000, chains=4, warmup=500, thin=1, seed=101)
```

**Comment by yezhengli-Mr9** [comment]
`stan_init` and `dat` are `pickle.dump(...)`ed from [python/fbprophet/forecaster.py#L1171](https://github.com/facebook/prophet/blob/8882c6a3e370736c382db14133f9c66f3b509c30/python/fbprophet/forecaster.py#L1171) and printed as following:
```python
	# print('[stan_init]', stan_init)
	# print('[dat]', dat)
	[stan_init] {'k': -0.05444079622224118, 'm': 0.7465517318876905, 'delta': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.]), 'beta': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'sigma_obs': 1}
[dat] {'T': 2905, 'K': 26, 'S': 25, 'y': 0       0.746552
1       0.663171
2       0.637023
3       0.628367
4       0.614441
          ...
2900    0.608498
2901    0.721885
2902    0.804388
2903    0.710364
2904    0.692111
Name: y_scaled, Length: 2905, dtype: float64, 't': 0       0.000000
1       0.000337
2       0.000675
3       0.001012
4       0.001350
          ...
2900    0.998650
2901    0.998988
2902    0.999325
2903    0.999663
2904    1.000000
Name: t, Length: 2905, dtype: float64, 't_change': array([0.03307459, 0.06513669, 0.10327371, 0.13533581, 0.16672292,
       0.19811002, 0.23152211, 0.2642592 , 0.2963213 , 0.33007087,
       0.36145798, 0.39284509, 0.4242322 , 0.4556193 , 0.4876814 ,
       0.5197435 , 0.55146811, 0.58285521, 0.61390483, 0.64529193,
       0.67667904, 0.70840364, 0.73979075, 0.77151536, 0.80290246]), 'X':       yearly_delim_1  yearly_delim_2  yearly_delim_3  ...  weekly_delim_4  weekly_delim_5  weekly_delim_6
0          -0.377462        0.926025       -0.699079  ...        0.623490   -9.749279e-01       -0.222521
1          -0.361478        0.932381       -0.674069  ...       -0.900969    7.818315e-01        0.623490
2          -0.345386        0.938461       -0.648262  ...       -0.222521   -4.338837e-01       -0.900969
3          -0.329192        0.944263       -0.621687  ...        1.000000   -5.291811e-12        1.000000
4          -0.312900        0.949786       -0.594376  ...       -0.222521    4.338837e-01       -0.900969
...              ...             ...             ...  ...             ...             ...             ...
2900        0.246857        0.969052        0.478434  ...       -0.900969   -7.818315e-01        0.623490
2901        0.263489        0.964662        0.508356  ...        0.623490    9.749279e-01       -0.222521
2902        0.280044        0.959987        0.537677  ...        0.623490   -9.749279e-01       -0.222521
2903        0.296516        0.955028        0.566362  ...       -0.900969    7.818315e-01        0.623490
2904        0.312900        0.949786        0.594376  ...       -0.222521   -4.338837e-01       -0.900969

[2905 rows x 26 columns], 'sigmas': [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0], 'tau': 0.05, 'trend_indicator': 0, 's_a': col
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
Name: additive_terms, dtype: int64, 's_m': col
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
Name: multiplicative_terms, dtype: int64, 'cap': array([0., 0., 0., ..., 0., 0., 0.])
```

**Comment by yezhengli-Mr9** [comment]
OK,
```python
import multiprocessing
multiprocessing.set_start_method("fork")
```
from [New to Pystan, Always get this error when attempting to sample: ModuleNotFoundError: No module named ‘stanfit4anon_model…’](https://discourse.mc-stan.org/t/new-to-pystan-always-get-this-error-when-attempting-to-sample-modulenotfounderror-no-module-named-stanfit4anon-model/19288/3)
